spring.application.name=Braindribbling Recipes
spring.thymeleaf.cache=false

app.log.level=INFO
app.secrets.base-name=recipe-secrets
spring.config.import=optional:classpath:secrets.properties,optional:file:/var/www/${app.secrets.base-name}.properties
