-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.recipes
(
    recipe_id serial NOT NULL,
    user_id integer NOT NULL,
    title character varying(255),
    description text,
    servings integer,
    recipe_note text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    recipe_visibility_id integer NOT NULL,
    PRIMARY KEY (recipe_id),
    UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.recipe_step_ingredient
(
    recipe_id integer NOT NULL,
    recipe_step_id integer NOT NULL,
    amount numeric(6, 2) NOT NULL,
    ingredient_id integer NOT NULL,
    measurement_id integer NOT NULL,
    ingredient_note text,
    CONSTRAINT recipe_step_ingredient_id PRIMARY KEY (recipe_step_id, ingredient_id),
    CONSTRAINT uniq_recipe_step_id_ingredient_id UNIQUE (ingredient_id, recipe_step_id)
);

CREATE TABLE IF NOT EXISTS public.ingredients
(
    ingredient_id serial NOT NULL,
    ingredient_name text NOT NULL,
    grocery_category_id integer NOT NULL,
    PRIMARY KEY (ingredient_id),
    CONSTRAINT uniq_ingredient_name UNIQUE (ingredient_name)
);

CREATE TABLE IF NOT EXISTS public.measurements
(
    measurement_id serial NOT NULL,
    unit_name text NOT NULL,
    abbreviation text,
    base_type_id integer NOT NULL,
    base_unit_equivalent numeric(10, 6) NOT NULL,
    scaling_rank smallint NOT NULL,
    PRIMARY KEY (measurement_id),
    CONSTRAINT uniq_unit_name UNIQUE (unit_name)
);

CREATE TABLE IF NOT EXISTS public.grocery_category
(
    grocery_category_id serial NOT NULL,
    category_name text NOT NULL,
    PRIMARY KEY (grocery_category_id),
    CONSTRAINT uniq_category_name UNIQUE (category_name)
);

CREATE TABLE IF NOT EXISTS public.base_type
(
    base_type_id serial NOT NULL,
    type_name text NOT NULL,
    PRIMARY KEY (base_type_id),
    CONSTRAINT uniq_type_name UNIQUE (type_name)
);

CREATE TABLE IF NOT EXISTS public.recipe_step
(
    recipe_step_id serial NOT NULL,
    recipe_id integer NOT NULL,
    step_number integer NOT NULL,
    instruction_text text NOT NULL,
    PRIMARY KEY (recipe_step_id),
    CONSTRAINT uniq_recipe_step_number UNIQUE (recipe_id, step_number)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    display_name text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    disabled_at timestamp with time zone,
    profile_visibility_id integer NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.users_auth
(
    users_auth_id serial NOT NULL,
    user_id integer NOT NULL,
    email text NOT NULL,
    password_hash text NOT NULL,
    password_changed_at timestamp with time zone NOT NULL DEFAULT now(),
    last_login timestamp with time zone,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (users_auth_id),
    CONSTRAINT uniq_email UNIQUE (email),
    UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    role_id serial NOT NULL,
    role_name text NOT NULL,
    description text,
    PRIMARY KEY (role_id),
    CONSTRAINT uniq_role_name UNIQUE (role_name)
);

CREATE TABLE IF NOT EXISTS public.user_roles
(
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    assigned_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.role_permissions
(
    role_id integer NOT NULL,
    permission_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.permissions
(
    permission_id serial NOT NULL,
    permission_name text NOT NULL,
    description text,
    PRIMARY KEY (permission_id),
    CONSTRAINT uniq_permission_name UNIQUE (permission_name)
);

CREATE TABLE IF NOT EXISTS public.login_history
(
    login_history_id serial NOT NULL,
    user_auth_id integer NOT NULL,
    login_at timestamp with time zone NOT NULL DEFAULT now(),
    ip_address text NOT NULL,
    user_agent text,
    is_successful boolean NOT NULL DEFAULT true,
    failure_reason text,
    PRIMARY KEY (login_history_id)
);

CREATE TABLE IF NOT EXISTS public.profile_visiblities
(
    profile_visibilitiy_id serial NOT NULL,
    profile_name text NOT NULL,
    description text,
    PRIMARY KEY (profile_visibilitiy_id),
    CONSTRAINT uniq_profile_name UNIQUE (profile_name)
);

CREATE TABLE IF NOT EXISTS public.recipe_visibilities
(
    recipe_visibility_id serial NOT NULL,
    visibility_name text NOT NULL,
    description text,
    PRIMARY KEY (recipe_visibility_id),
    CONSTRAINT uniq_visibility_name UNIQUE (visibility_name)
);

CREATE TABLE IF NOT EXISTS public.recipe_shares
(
    recipe_shares_id serial NOT NULL,
    recipe_id integer NOT NULL,
    shared_user_id integer,
    shared_token_id uuid,
    shared_at timestamp with time zone NOT NULL DEFAULT now(),
    access_level_id integer NOT NULL,
    PRIMARY KEY (recipe_shares_id)
);

CREATE TABLE IF NOT EXISTS public.access_levels
(
    access_level_id serial NOT NULL,
    access_name text NOT NULL,
    description text,
    PRIMARY KEY (access_level_id),
    CONSTRAINT uniq_access_name UNIQUE (access_name)
);

ALTER TABLE IF EXISTS public.recipes
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.recipes
    ADD FOREIGN KEY (recipe_visibility_id)
    REFERENCES public.recipe_visibilities (recipe_visibility_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.recipe_step_ingredient
    ADD FOREIGN KEY (ingredient_id)
    REFERENCES public.ingredients (ingredient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.recipe_step_ingredient
    ADD FOREIGN KEY (measurement_id)
    REFERENCES public.measurements (measurement_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.recipe_step_ingredient
    ADD FOREIGN KEY (recipe_step_id)
    REFERENCES public.recipe_step (recipe_step_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.recipe_step_ingredient
    ADD FOREIGN KEY (recipe_id)
    REFERENCES public.recipes (recipe_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.ingredients
    ADD FOREIGN KEY (grocery_category_id)
    REFERENCES public.grocery_category (grocery_category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.measurements
    ADD FOREIGN KEY (base_type_id)
    REFERENCES public.base_type (base_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.recipe_step
    ADD FOREIGN KEY (recipe_id)
    REFERENCES public.recipes (recipe_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.users
    ADD FOREIGN KEY (profile_visibility_id)
    REFERENCES public.profile_visiblities (profile_visibilitiy_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.users_auth
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.user_roles
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.user_roles
    ADD FOREIGN KEY (role_id)
    REFERENCES public.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.role_permissions
    ADD FOREIGN KEY (permission_id)
    REFERENCES public.permissions (permission_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.role_permissions
    ADD FOREIGN KEY (role_id)
    REFERENCES public.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.login_history
    ADD FOREIGN KEY (user_auth_id)
    REFERENCES public.users_auth (users_auth_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.recipe_shares
    ADD FOREIGN KEY (recipe_id)
    REFERENCES public.recipes (recipe_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.recipe_shares
    ADD FOREIGN KEY (shared_user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.recipe_shares
    ADD FOREIGN KEY (access_level_id)
    REFERENCES public.access_levels (access_level_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;